name: text_sizer_plus
description: Flutter widget that automatically resizes text to fit perfectly within its bounds.
version: 1.0.4
homepage: https://github.com/mufassalhussain/text_sizer_plus

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: '>=1.11.1 <3.0.0'